"""empty message

Revision ID: 1039f0ce997
Revises: cb78e1f749
Create Date: 2015-02-24 18:08:58.203568

"""

# revision identifiers, used by Alembic.
revision = '1039f0ce997'
down_revision = 'cb78e1f749'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('ip_address', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click', 'ip_address')
    ### end Alembic commands ###
