"""empty message

Revision ID: 10b32cf9459
Revises: 1039f0ce997
Create Date: 2015-02-24 20:06:25.682127

"""

# revision identifiers, used by Alembic.
revision = '10b32cf9459'
down_revision = '1039f0ce997'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
