"""empty message

Revision ID: 147ed53624f
Revises: 486bcb5a3c0
Create Date: 2015-02-23 18:34:43.717527

"""

# revision identifiers, used by Alembic.
revision = '147ed53624f'
down_revision = '486bcb5a3c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('ip', sa.String(length=15), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click', 'ip')
    ### end Alembic commands ###
