"""Adds link model

Revision ID: 1601b80f328
Revises: 7cb2209f80
Create Date: 2015-02-20 12:59:37.083761

"""

# revision identifiers, used by Alembic.
revision = '1601b80f328'
down_revision = '7cb2209f80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('long_link', sa.String(length=255), nullable=False),
    sa.Column('short_link', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_link')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    ### end Alembic commands ###
