"""empty message

Revision ID: 1911ffbe413
Revises: 32f33bfc296
Create Date: 2015-02-24 23:10:16.703447

"""

# revision identifiers, used by Alembic.
revision = '1911ffbe413'
down_revision = '32f33bfc296'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
