"""empty message

Revision ID: 1921f54c043
Revises: b22a5a81a6
Create Date: 2015-02-23 19:04:07.880037

"""

# revision identifiers, used by Alembic.
revision = '1921f54c043'
down_revision = 'b22a5a81a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=True),
    sa.Column('click_agent', sa.String(length=255), nullable=True),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['link.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    ### end Alembic commands ###
