"""empty message

Revision ID: 1e3ef06aab1
Revises: 220a8a8f916
Create Date: 2015-02-21 16:58:08.777890

"""

# revision identifiers, used by Alembic.
revision = '1e3ef06aab1'
down_revision = '220a8a8f916'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('when', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks', 'when')
    ### end Alembic commands ###
