"""empty message

Revision ID: 2068b783196
Revises: 4f867676232
Create Date: 2015-02-23 15:46:29.555679

"""

# revision identifiers, used by Alembic.
revision = '2068b783196'
down_revision = '4f867676232'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timestamps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timestamps')
    ### end Alembic commands ###
