"""empty message

Revision ID: 211e9ccc70f
Revises: 476ae5f4fe6
Create Date: 2015-02-20 23:16:30.968283

"""

# revision identifiers, used by Alembic.
revision = '211e9ccc70f'
down_revision = '476ae5f4fe6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
