"""empty message

Revision ID: 21abc8df181
Revises: 1d5cffe4ca9
Create Date: 2015-02-20 16:01:18.993843

"""

# revision identifiers, used by Alembic.
revision = '21abc8df181'
down_revision = '1d5cffe4ca9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('description', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmark', 'description')
    ### end Alembic commands ###
