"""empty message

Revision ID: 224c7a6ab6e
Revises: 3d8657006fa
Create Date: 2015-02-23 15:59:37.478598

"""

# revision identifiers, used by Alembic.
revision = '224c7a6ab6e'
down_revision = '3d8657006fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
