"""empty message

Revision ID: 23c1849f662
Revises: 2b3a02ac9dc
Create Date: 2015-02-25 17:00:40.449759

"""

# revision identifiers, used by Alembic.
revision = '23c1849f662'
down_revision = '2b3a02ac9dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
