"""empty message

Revision ID: 247b75fbbd8
Revises: 4b6b66fa579
Create Date: 2015-02-24 16:48:57.996264

"""

# revision identifiers, used by Alembic.
revision = '247b75fbbd8'
down_revision = '4b6b66fa579'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
