"""empty message

Revision ID: 24b4d47ac0e
Revises: 4a9399fe9c6
Create Date: 2015-02-23 13:34:23.477874

"""

# revision identifiers, used by Alembic.
revision = '24b4d47ac0e'
down_revision = '4a9399fe9c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
