"""empty message

Revision ID: 257eaaa1f92
Revises: 41ff68967f5
Create Date: 2015-02-22 15:10:19.927664

"""

# revision identifiers, used by Alembic.
revision = '257eaaa1f92'
down_revision = '41ff68967f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(length=10), nullable=True),
    sa.Column('original', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    ### end Alembic commands ###
