"""Added description to the link column.

Revision ID: 2617775e9b1
Revises: 1601b80f328
Create Date: 2015-02-22 19:07:21.496555

"""

# revision identifiers, used by Alembic.
revision = '2617775e9b1'
down_revision = '1601b80f328'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('description', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'description')
    ### end Alembic commands ###
