"""empty message

Revision ID: 29ba4082727
Revises: 4aa1e96528e
Create Date: 2015-02-23 21:09:13.705195

"""

# revision identifiers, used by Alembic.
revision = '29ba4082727'
down_revision = '4aa1e96528e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
