"""empty message

Revision ID: 2a578172891
Revises: 2d98f4f067a
Create Date: 2015-02-23 19:42:08.659153

"""

# revision identifiers, used by Alembic.
revision = '2a578172891'
down_revision = '2d98f4f067a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
