"""empty message

Revision ID: 2c18c6696ee
Revises: 8fd2803571
Create Date: 2015-02-25 01:47:35.991510

"""

# revision identifiers, used by Alembic.
revision = '2c18c6696ee'
down_revision = '8fd2803571'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
