"""empty message

Revision ID: 2d98f4f067a
Revises: 56fdb7071a6
Create Date: 2015-02-23 17:33:30.602189

"""

# revision identifiers, used by Alembic.
revision = '2d98f4f067a'
down_revision = '56fdb7071a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
