"""empty message

Revision ID: 2e44ebbd706
Revises: 224c7a6ab6e
Create Date: 2015-02-23 20:56:54.068517

"""

# revision identifiers, used by Alembic.
revision = '2e44ebbd706'
down_revision = '224c7a6ab6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('click_date', sa.DateTime(), nullable=True),
    sa.Column('bookmark_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookmark_id'], ['bookmark.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    ### end Alembic commands ###
