"""empty message

Revision ID: 2e888dd177b
Revises: 2617775e9b1
Create Date: 2015-02-22 19:13:38.891643

"""

# revision identifiers, used by Alembic.
revision = '2e888dd177b'
down_revision = '2617775e9b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['start_link'], ['link.short_link'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom')
    ### end Alembic commands ###
