"""empty message

Revision ID: 2fe63ae2a11
Revises: e41b3f969
Create Date: 2015-02-24 09:18:21.591734

"""

# revision identifiers, used by Alembic.
revision = '2fe63ae2a11'
down_revision = 'e41b3f969'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('user_ip_address', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click', 'user_ip_address')
    ### end Alembic commands ###
