"""empty message

Revision ID: 31d14e04414
Revises: 1fe07fcc512
Create Date: 2015-02-26 15:37:48.862140

"""

# revision identifiers, used by Alembic.
revision = '31d14e04414'
down_revision = '1fe07fcc512'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['link'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    ### end Alembic commands ###
