"""empty message

Revision ID: 32f33bfc296
Revises: 247b75fbbd8
Create Date: 2015-02-24 21:38:21.992877

"""

# revision identifiers, used by Alembic.
revision = '32f33bfc296'
down_revision = '247b75fbbd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
