"""empty message

Revision ID: 34c14327105
Revises: 1e3ef06aab1
Create Date: 2015-02-22 23:52:49.989169

"""

# revision identifiers, used by Alembic.
revision = '34c14327105'
down_revision = '1e3ef06aab1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
