"""empty message

Revision ID: 35137a16f17
Revises: 21abc8df181
Create Date: 2015-02-21 07:29:21.006190

"""

# revision identifiers, used by Alembic.
revision = '35137a16f17'
down_revision = '21abc8df181'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark__user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['bookmark.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark__user')
    ### end Alembic commands ###
