"""empty message

Revision ID: 3b7cdc51fb2
Revises: 2fe63ae2a11
Create Date: 2015-02-24 09:21:38.655976

"""

# revision identifiers, used by Alembic.
revision = '3b7cdc51fb2'
down_revision = '2fe63ae2a11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('user_agent', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click', 'user_agent')
    ### end Alembic commands ###
