"""empty message

Revision ID: 3bc54415868
Revises: 26858bc3682
Create Date: 2015-02-21 10:07:21.852659

"""

# revision identifiers, used by Alembic.
revision = '3bc54415868'
down_revision = '26858bc3682'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longurl', sa.String(length=255), nullable=False),
    sa.Column('shorturl', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    ### end Alembic commands ###
