"""empty message

Revision ID: 44c3546f1fc
Revises: 14df37a9370
Create Date: 2015-02-23 21:32:45.681792

"""

# revision identifiers, used by Alembic.
revision = '44c3546f1fc'
down_revision = '14df37a9370'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('ip', sa.String(length=255), nullable=True))
    op.add_column('click', sa.Column('user_agent', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click', 'user_agent')
    op.drop_column('click', 'ip')
    ### end Alembic commands ###
