"""empty message

Revision ID: 46282ffb664
Revises: b22a5a81a6
Create Date: 2015-02-23 13:43:55.508989

"""

# revision identifiers, used by Alembic.
revision = '46282ffb664'
down_revision = 'b22a5a81a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('click_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['click_link'], ['link.short_link'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    ### end Alembic commands ###
