"""empty message

Revision ID: 478d8a56e29
Revises: 645f82afe5
Create Date: 2015-02-20 09:35:27.682861

"""

# revision identifiers, used by Alembic.
revision = '478d8a56e29'
down_revision = '645f82afe5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urly_bird',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(length=255), nullable=False),
    sa.Column('long', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('long'),
    sa.UniqueConstraint('short')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urly_bird')
    ### end Alembic commands ###
