"""empty message

Revision ID: 486bcb5a3c0
Revises: 257eaaa1f92
Create Date: 2015-02-23 17:19:35.857628

"""

# revision identifiers, used by Alembic.
revision = '486bcb5a3c0'
down_revision = '257eaaa1f92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['link'], ['link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click')
    ### end Alembic commands ###
