"""empty message

Revision ID: 499f0a76947
Revises: 24b4d47ac0e
Create Date: 2015-02-23 13:52:02.798667

"""

# revision identifiers, used by Alembic.
revision = '499f0a76947'
down_revision = '24b4d47ac0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
