"""empty message

Revision ID: 4a9399fe9c6
Revises: 4ef57014343
Create Date: 2015-02-22 18:14:00.091381

"""

# revision identifiers, used by Alembic.
revision = '4a9399fe9c6'
down_revision = '4ef57014343'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
