"""empty message

Revision ID: 532ac75ea29
Revises: 10b32cf9459
Create Date: 2015-02-24 21:00:50.405258

"""

# revision identifiers, used by Alembic.
revision = '532ac75ea29'
down_revision = '10b32cf9459'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
