"""empty message

Revision ID: 54cefe892db
Revises: 1f87eb83704
Create Date: 2015-02-25 12:40:47.789429

"""

# revision identifiers, used by Alembic.
revision = '54cefe892db'
down_revision = '1f87eb83704'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
