"""empty message

Revision ID: 6d8848415
Revises: 499f0a76947
Create Date: 2015-02-23 16:11:43.275944

"""

# revision identifiers, used by Alembic.
revision = '6d8848415'
down_revision = '499f0a76947'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_links')
    op.add_column('links', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'links', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_column('links', 'user_id')
    op.create_table('user_links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('links_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['links_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
