"""empty message

Revision ID: 6dfa573194
Revises: 147ed53624f
Create Date: 2015-02-23 18:37:23.187359

"""

# revision identifiers, used by Alembic.
revision = '6dfa573194'
down_revision = '147ed53624f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('user_agent', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click', 'user_agent')
    ### end Alembic commands ###
