"""empty message

Revision ID: 911c15fecf
Revises: 23c1849f662
Create Date: 2015-02-25 17:07:07.447330

"""

# revision identifiers, used by Alembic.
revision = '911c15fecf'
down_revision = '23c1849f662'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
