"""empty message

Revision ID: b22a5a81a6
Revises: 2e888dd177b
Create Date: 2015-02-22 20:10:29.562100

"""

# revision identifiers, used by Alembic.
revision = 'b22a5a81a6'
down_revision = '2e888dd177b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom', sa.Column('new_link', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom', 'new_link')
    ### end Alembic commands ###
