"""empty message

Revision ID: cb78e1f749
Revises: 319c9a7edcd
Create Date: 2015-02-24 16:48:19.491682

"""

# revision identifiers, used by Alembic.
revision = 'cb78e1f749'
down_revision = '319c9a7edcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
