"""empty message

Revision ID: 1b0fbe43045
Revises: 394ce207666
Create Date: 2015-02-22 16:36:43.241021

"""

# revision identifiers, used by Alembic.
revision = '1b0fbe43045'
down_revision = '394ce207666'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
