"""empty message

Revision ID: 1f1dfdb45cc
Revises: 40a292bf19d
Create Date: 2015-02-20 08:49:59.885960

"""

# revision identifiers, used by Alembic.
revision = '1f1dfdb45cc'
down_revision = '40a292bf19d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
