"""empty message

Revision ID: 394ce207666
Revises: 37fe9ca64fd
Create Date: 2015-02-22 16:26:35.040768

"""

# revision identifiers, used by Alembic.
revision = '394ce207666'
down_revision = '37fe9ca64fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
