"""empty message

Revision ID: 486d1b4cbb0
Revises: None
Create Date: 2015-02-19 16:40:48.800796

"""

# revision identifiers, used by Alembic.
revision = '486d1b4cbb0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
