"""empty message

Revision ID: 15369890436
Revises: None
Create Date: 2015-02-19 23:00:33.568100

"""

# revision identifiers, used by Alembic.
revision = '15369890436'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
